project:
  type: website
  resources:
    - "**/*.c2pa"
  post-render:
    - 'find . -type d -name "figure-pdf" -exec rm -rf {} + -o -name "figure-beamer" -exec rm -rf {} + -o -name "mediabag" -exec rm -rf {} +'
website:
  repo-url: https://github.com/ssccsorg/ssccs
  site-url: https://docs.ssccs.org
  repo-subdir: docs
  repo-actions: [edit, issue]
  llms-txt: true
  page-footer: 
    left: "© [SSCCS Foundation](https://ssccs.org) &bull; [*CC BY-NC-ND 4.0*](https://creativecommons.org/licenses/by-nc-nd/4.0/)"
    right: 
      - icon: house
        href: https://ssccs.org
      - icon: envelope
        aria-label: email
        href: mailto:contact@ssccs.org
      - icon: github
        href: https://github.com/ssccsorg/ssccs
  sidebar:  
    collapse-level: 1
    contents:
        - href: index.qmd
          text: "Home"
        - auto: "*.{qmd,md}"
        
metadata-files:
  - ./_include/format.html.yml
latex-clean: false
format:
  html:
    directory-index: true
